### ISSUE TITLE
Split numerical data to maximize similarity score

### ISSUE THREAD

**Issue by keckelt** [phovea/phovea_processing_similarity#3]
Numerical data should be split in 2 Groups: 
1.  Start --> Cut
2.  Cut --> End

So that the similarity to the given data is maximized in one of groups.

**Comment by keckelt** [comment]
Ordino can stratify by threshold, generating 2 groups:
1. Values <= Threshold
1. Values > Threshold

The task should return the threshold in addition to score & group.
I guess the group name can be arbitrary as it gets generated dynamically, but 
- DATASET_NAME <= Threshold ; e.g.:  Alter <= 60
- DATASET_NAME > Threshold;   e.g. Alter > 60

should be fine

**Comment by mstreit** [comment]
Yes, it can be same name as shown in the group column:
![image](https://user-images.githubusercontent.com/4129755/34555991-e02e0f28-f134-11e7-8ac3-90a9822b35f0.png)
